import type { SocialLink } from "@/config/types";

export const socialSectionConfig = {
  title: "Elsewhere",
};

export const socialsConfig: SocialLink[] = [
  {
    id: "github",
    platform: "GitHub",
    handle: "@Prateek32177",
    href: "https://github.com/Prateek32177",
    icon: "github",
    action: "external",
    order: 1,
    enabled: true,
  },
  {
    id: "x",
    platform: "X (Twitter)",
    handle: "@Prateek32177",
    href: "https://x.com/Prateek32177",
    icon: "x",
    action: "external",
    tooltipDefault: "Message on X",
    order: 2,
    enabled: true,
  },
  {
    id: "peerlist",
    platform: "Peerlist",
    handle: "@hookflo",
    href: "https://peerlist.io/hookflo",
    icon: "peerlist",
    action: "external",
    order: 3,
    enabled: true,
  },
  {
    id: "discord",
    platform: "Discord",
    handle: "@hookflo",
    icon: "discord",
    action: "copy",
    copyValue: "hookflo",
    shortcutKey: "C",
    tooltipDefault: "Copy username",
    order: 4,
    enabled: false,
  },
  {
    id: "email",
    platform: "Email",
    handle: "hello@prateekjn.me",
    href: "mailto:hello@prateekjn.me",
    icon: "gmail",
    action: "mailto",
    tooltipDefault: "Send email",
    order: 5,
    enabled: true,
  },
  {
    id: "reddit",
    platform: "Reddit",
    handle: "u/prateekjn",
    href: "https://www.reddit.com/user/prateekjn/",
    icon: "reddit",
    action: "external",
    tooltipDefault: "Visit Reddit profile",
    order: 6,
    enabled: false,
  },
];
